import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import NavBar from '../parts/NavBar/NavBar'
import Footer from '../parts/Footer/Footer'
import { TextField, Button, InputBase } from '@material-ui/core'
import { makeStyles } from '@material-ui/core/styles'
import { FormspreeProvider } from '@formspree/react'
import { useForm, ValidationError } from '@formspree/react'
import rob from '../public/rob.svg'
import robo from '../public/robo.svg'

const useStyles = makeStyles(theme => ({
  but: {
    display: 'flex',
    width: '300px',
    alignSelf: 'center',
    flexDirection: 'column',
    zIndex: '200',
    opacity: '1',
    // backgroundColor: '#282C35',
    backgroundColor: '#40fff2',
    // backgroundColor: 'black', // testing
    color: 'black',
    height: '42px',
    fontSize: '25px',
    fontWeight: '600',
    "&:hover": {
      backgroundColor: "#0dbab1 !important"
    }
  },
  em: { // email input
    color: 'black',
    display: 'flex',
    width: 'fill',
    marginTop: '-4px',
    // position: 'absolute',
    // zIndex: '300',
    // width: 'stretch',
    width: '300px',
    // backgroundColor: '#63e'
    border: '1px solid black',
    borderRadius: theme.shape.borderRadius,
    height: '45px',
    paddingLeft: '10px',
    fontSize: '20px',
    marginBottom: '1px',
  },
}));

export default function Home() {
  

  const [state, handleSubmit] = useForm("meqvkeed");

  return (
  
  <FormspreeProvider project='s1719866435204808110'>
    <Head>
      <title>talkerAI</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="favicon.ico" />
    </Head>
    <NavBar/>

  <div className={styles.container} data-testid="Home">
    
    <div class="lineChange">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div> 
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </div>

    <div className={styles.content}>



      <div className={styles.conHigh}>
      
        <p className={styles.pitch}>Need eCommerce support? <span className={styles.customize}>Customization</span>?</p>
        <p className={styles.pitch}> Help with sales? Returns? Promos?</p>
        {/* <br/> */}
        <div className={styles.midMessage}>   {/* inline section: rob logo, <p>, rob */}
          <div className={styles.rob}><Image src={rob} layout="fill"/></div>
          <p className={styles.hF}>There's a chatbot for that</p>
          <div className={styles.rob2}><Image src={rob} layout="fill"/></div>
        </div>
        {/* <br/> */}
      </div>

      <div className={styles.conMid}>
        <p className={styles.pitch}>
          Add your <span className={styles.heavy}>email</span> & join the movement🌊
        </p>
        <p className={styles.pitch}>Promotional offers on the way⚡</p>
      </div>

      <div className={styles.conLow}>
        <p className={styles.hF} style={{}}>Don't miss out!</p>
        {/* <EmailList/> */}

        <form 
        action="https://talkerai.us6.list-manage.com/subscribe/post?u=
        0a9bdda258e3b9371a1aa2953&amp;id=c1e5730a85" method="post" id="mc-embedded-subscribe-form" 
        name="mc-embedded-subscribe-form" class="validate" target="_blank" noValidate>
          <div id="mc_embed_signup_scroll">
            {/* <label for="mce-EMAIL">Subscribe</label>
            <input type="email" name="EMAIL" class="email" 
            id="mce-EMAIL" placeholder="email address" required/> */}
            <InputBase type="email" name="EMAIL" id="mce-EMAIL" 
            className={useStyles().em} color="primary"
            placeholder="email@address.com" variant="outlined"/>
            {/* <InputBase className={styles.eI,useStyles().em} id="standard-basic"
                  placeholder="email@address.com" name="email" variant="outlined"/> */}
            {/* real people should not fill this in and expect good things 
            - do not remove this or risk form bot signups--> */}
            
            {/* <div class="clear"> */}
            <Button type="submit" value="Subscribe" name="subscribe" className={styles.eI,useStyles().but} 
            id="mc-embedded-subscribe" variant="contained" color="primary">
              Sign me up
            </Button>
          </div>
        </form>
      </div>

      

    </div>
  </div>
  <Footer/>
  </FormspreeProvider>
);


  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <NavBar/>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/master/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //     <Footer/>
  //   </div>
  // )
}
